class CODE:
    SUCCESS = (0, "SUCCESS")
    INVALID_PARAMETERS = (1, "INVALID_PARAMETERS")
    ARTICLE_NOT_FOUND = (2, "ARTICLE_NOT_FOUND")

    UNKNOWN_SEVER_ERROR = (999, "UNKNOWN_SEVER_ERROR")
