# Generated by Django 4.1.5 on 2023-01-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('nickname', models.CharField(max_length=500)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_couunt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app_article',
            },
        ),
    ]
