# Generated by Django 4.1.5 on 2023-01-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_viewable',
            field=models.BooleanField(default=True),
        ),
    ]
