# Generated by Django 4.1.5 on 2023-02-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
