# Generated by Django 4.1.5 on 2023-02-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_viewable",
            field=models.BooleanField(default=True),
        ),
    ]
