# Generated by Django 4.1.5 on 2023-02-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_comment_is_viewable"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
