# Generated by Django 4.1.5 on 2023-02-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_comment_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
